target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
  pod 'DropdownSearch', :git => 'https://github.com/isabellanoriega99/DropdownSearch.git', :tag => '1.0.0'

end
